### ISSUE TITLE
Notification doesn't show up on Android Wear

### ISSUE THREAD

**Issue by sandy-8925** [dougkeen/BartRunnerAndroid#20] opened 2017-10-05 17:05 UTC
I've noticed that when I select a particular train, and an ongoing notification is created, the notification doesn't show up on Android Wear. Is there any chance you could fix that?

**Comment by robertokl** [comment] 2017-10-05 20:45
I had it working back on 2015, but Doug never merged :( https://github.com/dougkeen/BartRunnerAndroid/pull/7

I tried to rebase but there are too many conflicts for me to work on it right now. Shouldn't be too complicated though: The problem is that the app uses ongoing notifications which doesn't play well with android wear, so just changing it to normal notifications should make it work.

**Comment by dougkeen** [comment] 2017-10-15 18:48
The work done by @robertokl is now merged, and should be available on the Play store release soon

**Closed by dougkeen** 2017-10-15 18:48 UTC
